version: '3.9'

services:

  db_cache:
    image: redis:7.0.0
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - mysql-network

  db:
    image: mysql:8.0.29
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./database:/var/lib/mysql
    depends_on:
      - db_cache
    networks:
      - mysql-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - mysql-network

  backend:
    image: over-engineered-backend

    volumes:
      - ./backend:/app
      - ./backend/node_modules:/app/node_modules
    ports:
      - 3000:3000

    build:
      context: ./backend
      dockerfile: Dockerfile

    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"

    networks:
      - mysql-network

    depends_on:
      - db

  frontend:
    image: over-engineered-frontend

    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

    ports:
      - 3001:3000

    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "true"
    command: npm start
    depends_on:
      - backend

volumes:
  node_modules:
networks:
  mysql-network:
    driver: bridge
